plugin_paths:
- examples/plugins
- ~/.quantum-cli/plugins
- /Users/atamrak1/dev/rnd/quantum/quantum-cli-sdk
profile: dev
profiles:
  benchmark:
    caching: false
    log_level: INFO
    optimization_level: 0
    shots: 1000
    simulator: all
    validate_circuits: false
  dev:
    cache_dir: .quantum_cache
    cache_max_age: 86400
    caching: true
    log_level: DEBUG
    optimization_level: 1
    optimization_pipeline: default
    shots: 1024
    simulator: qiskit
    validate_circuits: true
  prod:
    cache_dir: .quantum_cache
    caching: false
    log_level: WARNING
    optimization_level: 3
    optimization_pipeline: optimized
    shots: 8192
    simulator: qiskit
    validate_circuits: true
  test:
    cache_dir: .quantum_cache
    cache_max_age: 604800
    caching: true
    log_level: INFO
    optimization_level: 2
    optimization_pipeline: default
    shots: 4096
    simulator: cirq
    validate_circuits: true
quantum_providers:
  aws:
    region: us-east-1
    s3_bucket: null
  google:
    project_id: null
  ibm:
    group: open
    hub: ibm-q
    project: main
    token: YOUR_IBM_TOKEN
