# Quantum Project Configuration

# Project Information
project:
  name: Quantum Project
  version: 0.1.0
  description: A quantum computing project created with Quantum CLI SDK

# Quantum Settings
quantum:
  # Default backend for simulations
  default_backend: qiskit  # Options: qiskit, cirq, braket
  
  # Optimization level (0-3, higher means more optimization)
  optimization_level: 1
  
  # Default number of shots for circuit execution
  default_shots: 1024
  
  # Error mitigation settings
  error_mitigation:
    enabled: true
    methods:
      - readout
      - zne
  
  # Hardware settings
  hardware:
    enabled: false
    # provider: ibm  # Uncomment to enable hardware execution
    # device: ibmq_qasm_simulator  # Simulator for testing

# API Settings
api:
  enabled: true
  host: localhost
  port: 8000
  # auth_required: false  # Uncomment for API authentication

# Logging Settings
logging:
  level: INFO  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_logging:
    enabled: true
    path: logs/quantum.log
    max_size: 10  # MB
    backup_count: 3

# For custom backends or plugins
plugins:
  paths:
    - ~/.quantum/plugins
    - ./plugins

# Advanced Settings
advanced:
  transpiler:
    custom_passes:
      enabled: false
      # path: ./custom_passes  # Uncomment to load custom passes
  
  cache:
    enabled: true
    path: .quantum_cache
    max_age: 86400  # Cache data lifetime in seconds (24 hours) 